name: CI
on: push


jobs:
  test:
    name: CI
    runs-on: macos-latest
    steps:
        - name: Checkout
          uses: actions/checkout@master
        - name: Build and test
          run: | 
            xcodebuild -scheme Camera\ Bop -configuration Release
