name: CI
on:
  push:
    branches:
      - master


jobs:
  test:
    name: CI
    runs-on: macos-latest
    steps:
        - name: Checkout
          uses: actions/checkout@master
        - name: Setup Code-Sign
          uses: apple-actions/import-codesign-certs@v1
          with:
            p12-file-base64: ${{ secrets.CERT_P12_BASE64 }}
            p12-password: ${{ secrets.CERT_P12_PASSWD }}
        - name: Build and test
          run: | 
            xcodebuild -scheme Camera\ Bop -configuration Release
